version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: open-graph-scraper
    versions:
    - 4.7.1
    - 4.8.1
  - dependency-name: hexo
    versions:
    - 5.3.0
